language: erlang
arch:
   - ppc64le
   - amd64

otp_release:
   - 22.0
   - 23.0

sudo: false

addons:
  apt:
    packages:
      - build-essential

branches:
  only:
    - master

script:
  - "make"
  - "make tests"

# notifications:
#   email:
#     recipients:
#       - 
#     on_success: change
#     on_failure: always
